import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import classNames from 'classnames';
import Body from '@/common/layout/body';
import Head from '@/common/layout/head';
import Html from '@/common/layout/html';
import Root from '@/common/layout/root';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const fontBody = Roboto({
  subsets: ['vietnamese'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['300', '400', '500', '700']
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Html>
      <Head />
      <Body className={classNames(fontBody.variable, 'font-roboto text-default-text')}>
        <Root>{children}</Root>
      </Body>
    </Html>
  );
}
